BEGIN;

ALTER TABLE companies
  ADD COLUMN slug text;

UPDATE companies
SET slug = id::text
WHERE slug IS NULL;

ALTER TABLE companies
  ALTER COLUMN slug SET NOT NULL,
  ADD CONSTRAINT companies_slug_unique UNIQUE (slug),
  ADD CONSTRAINT companies_slug_format CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$');

ALTER TABLE users FORCE ROW LEVEL SECURITY;
ALTER TABLE company_modules FORCE ROW LEVEL SECURITY;
ALTER TABLE customers FORCE ROW LEVEL SECURITY;
ALTER TABLE sales FORCE ROW LEVEL SECURITY;
ALTER TABLE installments FORCE ROW LEVEL SECURITY;
ALTER TABLE payments FORCE ROW LEVEL SECURITY;
ALTER TABLE customer_notes FORCE ROW LEVEL SECURITY;
ALTER TABLE refresh_sessions FORCE ROW LEVEL SECURITY;
ALTER TABLE audit_events FORCE ROW LEVEL SECURITY;
ALTER TABLE suppression_entries FORCE ROW LEVEL SECURITY;

COMMIT;

